### ISSUE TITLE
404 Error Message

### ISSUE THREAD

**Issue by tonijaa007** [microsoft/AzureDevOpsDemoGenerator#1092]
Hi, i´m following the Microsoft Learning Path for DevOps and there i have to create a project based on different templates. 
Link: https://azuredevopsdemogenerator.azurewebsites.net/environment/createproject
When clicking on "Navigate to project" i´m getting a 404 error, page not found.

**Comment by HassanFad** [comment]
Hi,

Thanks for trying the usage of Azure DevOps Demo generator.
To work around the issue, Check the organization settings, Policies and enable the option as listed in the attachement.

Please do follow up of the issue is solved or not after trying.

Thanks,

Best Regards,

Hassan Fadili
MVP DevOps (Azure DevOps and GitHub)



Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________
From: Osman Rahimi ***@***.***>
Sent: Friday, December 27, 2024 10:05:05 AM
To: microsoft/AzureDevOpsDemoGenerator ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/AzureDevOpsDemoGenerator] 404 Error Message (Issue #1092)


Hi, i´m following the Microsoft Learning Path for DevOps and there i have to create a project based on different templates.
Link: https://azuredevopsdemogenerator.azurewebsites.net/environment/createproject
When clicking on "Navigate to project" i´m getting a 404 error, page not found.

**Comment by tonijaa007** [comment]
Hi, which attachment? Nothing was attached, at least i can´t see a document or something similar..

**Comment by HassanFad** [comment]
Hi Osman,

I have attached a picture mentioning the setting you have to change on your Azure DevOps Organization level.

I hope this helpt.

Thanks

Best Regards,

Hassan Fadili

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tonijaa007** [comment]
I´m sorry but there is no picture. I´m checking your message via outlook and nothing is there attached. Also from github i can´t see anything. Can you please attach the picture again? Also if i´m clicking on this link https://aka.ms/AAb9ysg it just shows me the outlook logo and "get it on google play" or  "download on the app store". But beside that there is nothing.

**Comment by HassanFad** [comment]
Very strenge. There is an attachment (pic) attached twice.
Otherwise, please go to the Azure DevOps Organisation selected for the creation of the project from demo generator, then select Policies, then enable the 1st option mentioning ""Third-party Application Access via OAuth" and try the project creation again.

I hope this helpt.

Best Regards

Hassan Fadili

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by tonijaa007** [comment]
Thank you very much, it worked!

**Comment by HassanFad** [comment]
Thanks for the feedback and glad that it worked.

Best Regards,

Hassan Fadili
MVP DevOps and GitHub

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________
