### ISSUE TITLE
Multiple Teams no work Items deployed

### ISSUE THREAD

**Issue by andoius** [microsoft/AzureDevOpsDemoGenerator#280]
I have a project with 6 teams and one of the teams has 12 stories and 1 - 4 tasks per story.
Creating a template from this contains the stories and tasks, however, creating a project from this template does not deploy the tasks or stories

**Comment by aksh-h** [comment]
Hi @andoius,

Is it possible to share the template? So that we can inspect.

**Comment by andoius** [comment]
Sure I can share it but I would need to send it directly as it needs to stay out of the public domain.

not sure if it helps in the meantime but all I get is:
- Project DLAF_V1.3 created
- 7 team(s) created
- Board-Column, Swimlanes, Styles updated

**Comment by aksh-h** [comment]
Alright!! Here is my [email](mailto:akshay.hosur@ecanarys.com)

**Comment by aksh-h** [comment]
Thank you for sharing template file, we will inspect.

**Comment by aksh-h** [comment]
Hi @andoius , We found out problem with the template. 

## Inspection
You have the area path other than the team name in the work item, as shown here
```
"System.AreaPath": "$ProjectName$\\Infrastructure"
```

Your team names are as shown below
```
"name": "Customer Infrastructure",
"name": "Coeo Infrastructure",
````
It is recommended to have the team areas in the work items area path, so it can be able to import back.Tool creates area path based on the team name, the format will be ```ProjectName\TeamName```.

So, based on above details, since area path is different from team area, tool couldn't map the work item to team area. Hence the work items are not creating.

## Resolution
In two ways you can correct this

1.  You can bring all the work items to a team area in your primary project. Then try exporting using **Template Builder**
1.  Modify the area paths in you work item JSON files to the required Team Name
> ex: "System.AreaPath": "$ProjectName$\\Customer Infrastructure"
    You can copy and paste the same to all the work items.
