### ISSUE TITLE
getting the below error while creating demo project

### ISSUE THREAD

**Issue by rajesh929** [microsoft/AzureDevOpsDemoGenerator#292]
Request was blocked due to exceeding usage of resource 'Concurrency' in namespace 'VSID'. For more information on why your request was blocked, see the topic "Rate limits" on the Microsoft Web site (https://go.microsoft.com/fwlink/?LinkId=823950).

**Comment by aksh-h** [comment]
Hi @rajesh929, Thank you for reaching us.
Requests won't be blocked when you are using Demo Generator, because this hardly takes 2-3 mins to create project with few calls to the server.  You can find more insights on rate limits [here](https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/rate-limits?view=azure-devops)
