### ISSUE TITLE
Importing Template as a new Project not possible - no process template found

### ISSUE THREAD

**Issue by JanWurm** [microsoft/AzureDevOpsDemoGenerator#316]
Hello Guys,
i'm tring to setup a new version of my already existing Demo Project. Now i got following error after clicking "create project":

VS402362: No process template with type <with my GUID> was found.
I successfuly downloaded, some minutes before, the project.

I do not get any better error message by the system. Pls assist :)

**Comment by aksh-h** [comment]
Hello @JanWurm Thank you for reaching us.
Looks like you are using custom or inherited process template in the source organization.

In order to import the project template and create a new project, target organization must have the same process template id.

Please have a look at limitation [document](https://github.com/microsoft/AzureDevOpsDemoGenerator/blob/master/docs/Limitations.md)

Let us know if you have any queries.
Thanks.

**Comment by JanWurm** [comment]
Hey, thanks for the fast response!
Yes, i'm using custom process. 

So it is not possible to copy this procress whithin the template?

**Comment by aksh-h** [comment]
No, process template can't be copied
