### ISSUE TITLE
Request access

### ISSUE THREAD

**Issue by MGodfrey50** [microsoft/AzureDevOpsDemoGenerator#319]
Hi - can you provide me sufficient permissions to "Create new projects."  I am trying to start the Azure Sentinal DevOps environment.
Thank you
Mark

**Comment by dmckinstry** [comment]
Hi @MGodfrey50,

The permissions to create new products isn't a side-effect of the AzureDevOpsDemoGenerator.  Instead, this problem is usually due to the Azure DevOps organization that you're deploying to (e.g., https://dev.azure.com/*myOrg*).  Can you check permissions with your Azure DevOps administrator.  Or, if you'd rather, you can create a new org for free in which you're the owner and have full permissions.  Obviously that wouldn't be the same as your production Azure DevOps org but should get around the permissions problem if you just need to use it as a reference.

Let us know if this help.

Thanks,
-Dave

**Comment by aksh-h** [comment]
Hope the information is adequate. Hence closing the issue.
