### ISSUE TITLE
Create New Template Error while querying work items

### ISSUE THREAD

**Issue by einolip** [microsoft/AzureDevOpsDemoGenerator#343]
regardless of team project getting next error "Error while querying work items: VS403474: You requested 336 work items which exceeds the limit of 200"
![image](https://user-images.githubusercontent.com/72126530/97584938-3e73d480-1a01-11eb-89c3-47774c20e236.png)
Requested item count does not change

[AB#3526](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3526)

**Comment by aksh-h** [comment]
Hi @einolip Thank you for posting here.

We are aware of this issue, we reported this to products team since the error returning is an API response.
currently we don't have recommended solution for this. You can follow the similar thread [here](https://developercommunity.visualstudio.com/content/problem/1195820/vs403474-you-requested-484-work-items-which-exceed.html)

Note: This occurs randomly, we suggest you try in after sometime.

Thanks.

**Comment by einolip** [comment]
it (thread [here](https://developercommunity.visualstudio.com/content/problem/1195820/vs403474-you-requested-484-work-items-which-exceed.html)) has "Closed - Not Enough Info" status since last year

**Comment by aksh-h** [comment]
It is not last year, it's a month ago in September. You can follow the thread and see we have shared all the necessary info.

Did you try it again?
