### ISSUE TITLE
Error while creating wiki: TF401019: The Git repository with name or identifier 8638BA9F-0383-4616-A1BC-B84051FEFF8C does not exist or you do not have permissions for the operation you are attempting.

### ISSUE THREAD

**Issue by NAVJuanan** [microsoft/AzureDevOpsDemoGenerator#362]
Error while creating wiki: TF401019: The Git repository with name or identifier 8638BA9F-0383-4616-A1BC-B84051FEFF8C does not exist or you do not have permissions for the operation you are attempting.

[AB#3566](https://vstsdemodata.visualstudio.com/89b9b739-9a1c-4739-8aae-6a8a1eb67ee7/_workitems/edit/3566)

**Comment by aafvstam** [comment]
![image](https://user-images.githubusercontent.com/5305682/103138347-de806e00-46d1-11eb-8cb1-6659aa27abca.png)
Same here ... tried several times with and without creating Fork.

**Comment by aafvstam** [comment]
As usual ... the issue is solved by removing the space from the project name.
I was generating the project named "Tailwind Traders" as instructed resulting in the error above.
Creating the same thing after cleaning up and naming the project TailwindTraders it properly finished generating all items.

![image](https://user-images.githubusercontent.com/5305682/103139094-3c648400-46d9-11eb-95f4-c95c1d3304f5.png)

**Comment by NAVJuanan** [comment]
> As usual ... the issue is solved by removing the space from the project name.
> I was generating the project named "Tailwind Traders" as instructed resulting in the error above.
> Creating the same thing after cleaning up and naming the project TailwindTraders it properly finished generating all items.
> 
> ![image](https://user-images.githubusercontent.com/5305682/103139094-3c648400-46d9-11eb-95f4-c95c1d3304f5.png)

It works! Thank u

**Comment by aksh-h** [comment]
Thank you posting your comment with resolution.
