### ISSUE TITLE
Error on creating Project from template

### ISSUE THREAD

**Issue by sebastianhubersw1** [microsoft/AzureDevOpsDemoGenerator#572]
Hello

If I try to create a project from a own template, I get the following error message.

VS402362: No process template with type 9869c11d-ca61-4c8e-9c95-3b7498f9aa8a was found.

As template I use a template export from one of my own private projects.

Thanks

**Comment by aksh-h** [comment]
Hi @sebastianhubersw1,
Thank you for reaching us. Looks like your project using inherited or any custom process template. 
In order to provision a new project, the source and target organization must have the same process template. You can change the process template Id or name in the ```ProjectSetting.json``` file of your zip downloaded template.
